version: "3.9"

services:
  web:
    build: .
    container_name: srrs_web
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: postgres:latest
    container_name: srrs_db
    environment:
      POSTGRES_DB: srrs_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  pgadmin:
      image: dpage/pgadmin4
      container_name: srrs_pgadmin
      environment:
        PGADMIN_DEFAULT_EMAIL: cybersam544@gmail.com
        PGADMIN_DEFAULT_PASSWORD: admin
      ports:
        - "5050:80"
      depends_on:
        - db